### ISSUE TITLE
Submit a py-flake8 patch

### ISSUE THREAD

**Issue by snsinfu** [frickiericker/freebsd-portdev-pipenv#3]
py-pipenv depends on py-flake8, which has a missing dependency problem:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219648

I will create and submit a patch.

**Comment by snsinfu** [comment]
Error message:
```
$ pipenv
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3038, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3022, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3051, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 971, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 857, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by flake8
```

**Comment by snsinfu** [comment]
Created a patch: e2b0acd5b10ca0799c53a3b5bf9f9468f52a58ca.  And [submitted](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219648).
